const { commentIDs, userIDs, postIDs } = require('./test_IDs');

exports.comments = [
    {
        _id: commentIDs[0],
        post: postIDs[0],
        author: userIDs[1],
        timestamp: new Date('2023-10-07T00:10:00'),
        body: 'comment0',
        likes: [],
        replies: [commentIDs[4]],
        isReply: false,
    },
    {
        _id: commentIDs[1],
        post: postIDs[2],
        author: userIDs[0],
        timestamp: new Date('2023-10-07T01:10:00'),
        body: 'comment1',
        likes: [],
        replies: [],
        isReply: false,
    },
    {
        _id: commentIDs[2],
        post: postIDs[1],
        author: userIDs[2],
        timestamp: new Date('2023-10-07T02:10:00'),
        body: 'comment2',
        likes: [],
        replies: [],
        isReply: false,
    },
    {
        _id: commentIDs[3],
        post: postIDs[2],
        author: userIDs[1],
        timestamp: new Date('2023-10-07T03:10:00'),
        body: 'comment3',
        likes: [],
        replies: [],
        isReply: false,
    },
    {
        _id: commentIDs[4],
        post: postIDs[0],
        author: userIDs[2],
        timestamp: new Date('2023-10-07T01:10:00'),
        body: 'reply0',
        likes: [],
        replies: [],
        isReply: true,
    },
];
